### PR TITLE
Improving the EDID Cleaner for Xrandr

### PR DESCRIPTION
**Pull request by hyades**
The following commits include the following - 

- Some old packages updated
- Improved EDID Cleaner for Xrandr
- Unittest for checking output of cleaner
- Updated gitignore (few files were generated as part of `make install`. Added them to ignore list. Not sure why it was not the case earlier)

### CODE REVIEW

**Comment by mithro** [comment]
So, it looks like the Travis build is failing. Can you see if you can fix that?

**Comment by hyades** [comment]
Not sure here. Seems an issue with the selenium tests which are unable to load the X environment correctly.

` Firefox output: Xlib:  extension "RANDR" missing on display ":99.0"`

**Comment by mithro** [comment]
The xrandr missing is a red herring and I believe unrelated to the failure. The real failure seems to be;
```
[CustomizableUI]\n  Custom widget with id loop-button does not return a valid node\n*** Blocklist::_preloadBlocklistFile: blocklist is disabled\n1484085615219\taddons.manager\tDEBUG\tStarting provider: <unnamed-provider>\n1484085615219\taddons.manager\tDEBUG\tRegistering shutdown blocker for <unnamed-provider>\n1484085615219\taddons.manager\tDEBUG\tProvider finished startup: <unnamed-provider>\nJavaScript warning: https://normandy.cdn.mozilla.net/static/bundles/selfrepair-133d4d7c9de72117ee8e.24ec5279eef1.js, line 7: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create\nJavaScript error: https://normandy.cdn.mozilla.net/static/bundles/selfrepair-133d4d7c9de72117ee8e.24ec5279eef1.js, line 9: ReferenceError: fetch is not defined\n' 
```

**Comment by mithro** [comment]
Are you able to run the tests locally on your computer?

**Comment by mithro** [comment]
@pp3345 Is anything in this pull request still useful? Should I close it?

**Comment by pp3345** [comment]
@mithro I guess the xrandr cleaner improvements might still be useful. I'll have a look at it later and decide whether to cherry-pick some of the changes.

**Comment by pp3345** [comment]
@hyades I've rebased and updated your changes to be compatible with the current version of edid.tv and created a new PR here: https://github.com/timvideos/edid.tv/pull/34 Thanks a lot for your contribution!

**Pull request closed without merging**
