### PR TITLE
Upgrade to Django 1.11

### PR DESCRIPTION
**Pull request by pp3345**
This took quite a bit longer than expected and still isn't 100% complete but this is what I have so far (**WIP**, so please don't merge yet). Django 1.11 is the latest release that still supports Python 2.7.

@mithro It seems that Travis CI is currently turned off for this repo, could you please enable it again?

### TODO
- [x] Four revision-related test cases are still failing (I suspect this only ever worked due to a bug in `django-reversion` and our stuff is now broken because that bug was fixed)
- [x] `django-reversion` made one of its properties private, figure out how to fix this without accessing that property
- [x] Make Selenium work again
- [x] The `Makefile` probably needs some more updates

### CODE REVIEW

**Comment by pp3345** [comment]
Selenium should be fine again now. The previous integration basically stopped working with Firefox 43, GeckoDriver is now required for testing with Firefox. Most tests were quite flaky, I've fixed that by introducing proper explicit wait conditions. One of the tests is still failing but that's related to the other revision-related test cases.

**Comment by mithro** [comment]
This is looking pretty good for me!

**Comment by pp3345** [comment]
All issues except for the Makefile are resolved now and all tests are green. 

@mithro As previously asked, could you please enable Travis again? I'm also thinking about removing the Makefile altogether as I fail to see the point of having one for a simple Python/Django web project. We could just add the few commands that are actually needed for quick-starting into the project to the README instead. What do you think?

**Comment by mithro** [comment]
Travis-CI reactivated. You will need a to push something to get it to run however.

**Comment by pp3345** [comment]
@mithro Thanks for enabling Travis. What do you think about the Makefile question?

**Comment by pp3345** [comment]
No, I am fine with keeping the Makefile. I've fixed the remaining stuff and also updated the Travis configuration. The Travis builds are failing because of some pep8 and pylint stuff which I feel belongs into another PR. This PR is ready from my side.

**Comment by pp3345** [comment]
@mithro friendly ping :)

**Comment by mithro** [comment]
Merged!

**Pull request merged**
