### PR TITLE
Allow downloading EDID binaries

### PR DESCRIPTION
**Pull request by pp3345**
This PR adds a download button to the EDID detail view and allows downloading the binaries.

Fixes: https://github.com/timvideos/edid.tv/issues/11

### CODE REVIEW

**Comment by pp3345** [comment]
Updated the commit: `monitor_name` isn't necessarily set, so check whether it is. Also include the serial number.

**Comment by mithro** [comment]
Thanks!

**Comment by mungewell** [comment]
Nice that this has been implemented, thanks.

But it's not available on the public web-server, when is that likely to happen?
Simon.

**Comment by pp3345** [comment]
@mungewell I am working on deploying the updated site, however, I am still waiting for a file I've requested from @mithro.

@mithro Did you see my e-mails? ;-)

**Comment by mithro** [comment]
No I didn't see your emails... Looking now...

**Pull request merged**
