### PR TITLE
Include all Python files recursively again in Travis pylint

### PR DESCRIPTION
**Pull request by pp3345**
This implements a variation of @mithro's suggestion from https://github.com/timvideos/edid.tv/pull/28

### CODE REVIEW

**Comment by pp3345** [comment]
This is probably the ugliest bash command I've ever written, but it works :man_shrugging:

**Comment by pp3345** [comment]
Looking at this again, I am an idiot. Here is a much simpler and saner solution.

For reference, the previous approach was
```bash
pylint --reports=n *.py $(find -type d \( -path "./frontend*" -o -path "./edid_parser*" \) -exec sh -c 'ls -1 {}/*.py 2> /dev/null | (test $(wc -l) -gt 0 && echo {})' ';' | awk '{ print $1 "/*.py" }')
```

**Comment by mithro** [comment]
I think you want something like this 
```shell
$(find ./frontend* ./edid_parser* -type f -and -name \*.py -and -not -empty)
```

**Comment by pp3345** [comment]
I think the current solution is okay, what do you think? Requiring `shopt` is a bit unfurtonate, but apart from that... If you prefer using `find` I am okay with that, too, of course.

**Comment by mithro** [comment]
One find command is superior to one find command + ls + awk...

**Comment by mithro** [comment]
Oh - I didn't see the `shopt` change...

**Comment by pp3345** [comment]
Sure, but that's not the solution used by the current commit.

**Pull request merged**
