### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by pp3345**
This branch upgrades the project to Python 3.7 and removes compatibility for Python 2.

### CODE REVIEW

**Comment by mithro** [comment]
```
0.13s$ coverage run --source=edid_parser edid_parser/tests.py
Traceback (most recent call last):
  File "edid_parser/tests.py", line 6, in <module>
    from .edid_parser import (EDIDParser, EDIDParsingError, DisplayType,
ModuleNotFoundError: No module named '__main__.edid_parser'; '__main__' is not a package
The command "coverage run --source=edid_parser edid_parser/tests.py" exited with 1.
```

**Comment by pp3345** [comment]
Yeah, looking into that now.

**Comment by mithro** [comment]
```
0.08s$ pycodestyle --statistics --exclude=wsgi.py *.py
path.py:2:16: W292 no newline at end of file
1       W292 no newline at end of file
The command "pycodestyle --statistics --exclude=wsgi.py *.py" exited with 1.
```

**Comment by pp3345** [comment]
Okay, everything is green now.

**Pull request merged**
